title: AI talks
author: Oleksandr Davyskyba
description: I share my thoughts about AI and where it all is going.
github_username:  zviryatko
theme: minima
url: "https://zviryatko.github.io"
minima:
  show_excerpts: true
  nav_pages:
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/zviryatko"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/zviryatko/"
  skin: auto
  hide_site_feed_link: true
google_analytics: G-6G5LPB7WEB
feed:
  posts_limit: 9999
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
